I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/hermanHub.rpy", line 22, in script
    if attitude >= 0:
  File "game/hermanHub.rpy", line 22, in <module>
    if attitude >= 0:
NameError: name 'attitude' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/hermanHub.rpy", line 22, in script
    if attitude >= 0:
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Owner\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/hermanHub.rpy", line 22, in <module>
    if attitude >= 0:
NameError: name 'attitude' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
The House On Limbo Lane 1.0
Sun Oct  1 01:12:54 2023
